# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\x07metrics\"}\n\x0eMetricsRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07latency\x18\x02 \x01(\x01\x12\x0e\n\x06jitter\x18\x03 \x01(\x01\x12\x13\n\x0bpacket_loss\x18\x04 \x01(\x01\x12\x11\n\tbandwidth\x18\x05 \x01(\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"\"\n\x0fMetricsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\x0c\x46\x65tchRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"v\n\x07Metrics\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07latency\x18\x02 \x01(\x01\x12\x0e\n\x06jitter\x18\x03 \x01(\x01\x12\x13\n\x0bpacket_loss\x18\x04 \x01(\x01\x12\x11\n\tbandwidth\x18\x05 \x01(\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"0\n\x0bMetricsList\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.metrics.Metrics2\x91\x01\n\x0eMetricsService\x12\x42\n\rSubmitMetrics\x12\x17.metrics.MetricsRequest\x1a\x18.metrics.MetricsResponse\x12;\n\x0c\x46\x65tchMetrics\x12\x15.metrics.FetchRequest\x1a\x14.metrics.MetricsListB\x15Z\x13pkg/api/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023pkg/api/proto;proto'
  _globals['_METRICSREQUEST']._serialized_start=26
  _globals['_METRICSREQUEST']._serialized_end=151
  _globals['_METRICSRESPONSE']._serialized_start=153
  _globals['_METRICSRESPONSE']._serialized_end=187
  _globals['_FETCHREQUEST']._serialized_start=189
  _globals['_FETCHREQUEST']._serialized_end=220
  _globals['_METRICS']._serialized_start=222
  _globals['_METRICS']._serialized_end=340
  _globals['_METRICSLIST']._serialized_start=342
  _globals['_METRICSLIST']._serialized_end=390
  _globals['_METRICSSERVICE']._serialized_start=393
  _globals['_METRICSSERVICE']._serialized_end=538
# @@protoc_insertion_point(module_scope)
