// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/api/proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Latency       float64                `protobuf:"fixed64,2,opt,name=latency,proto3" json:"latency,omitempty"`
	Jitter        float64                `protobuf:"fixed64,3,opt,name=jitter,proto3" json:"jitter,omitempty"`
	PacketLoss    float64                `protobuf:"fixed64,4,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	Bandwidth     float64                `protobuf:"fixed64,5,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_pkg_api_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MetricsRequest) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *MetricsRequest) GetJitter() float64 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

func (x *MetricsRequest) GetPacketLoss() float64 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *MetricsRequest) GetBandwidth() float64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *MetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_pkg_api_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_pkg_api_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *FetchRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Latency       float64                `protobuf:"fixed64,2,opt,name=latency,proto3" json:"latency,omitempty"`
	Jitter        float64                `protobuf:"fixed64,3,opt,name=jitter,proto3" json:"jitter,omitempty"`
	PacketLoss    float64                `protobuf:"fixed64,4,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	Bandwidth     float64                `protobuf:"fixed64,5,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_pkg_api_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *Metrics) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Metrics) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *Metrics) GetJitter() float64 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

func (x *Metrics) GetPacketLoss() float64 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *Metrics) GetBandwidth() float64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *Metrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MetricsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Metrics             `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsList) Reset() {
	*x = MetricsList{}
	mi := &file_pkg_api_proto_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsList) ProtoMessage() {}

func (x *MetricsList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsList.ProtoReflect.Descriptor instead.
func (*MetricsList) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsList) GetEntries() []*Metrics {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_pkg_api_proto_metrics_proto protoreflect.FileDescriptor

const file_pkg_api_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/api/proto/metrics.proto\x12\ametrics\"\xb8\x01\n" +
	"\x0eMetricsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\alatency\x18\x02 \x01(\x01R\alatency\x12\x16\n" +
	"\x06jitter\x18\x03 \x01(\x01R\x06jitter\x12\x1f\n" +
	"\vpacket_loss\x18\x04 \x01(\x01R\n" +
	"packetLoss\x12\x1c\n" +
	"\tbandwidth\x18\x05 \x01(\x01R\tbandwidth\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"+\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\fFetchRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xb1\x01\n" +
	"\aMetrics\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\alatency\x18\x02 \x01(\x01R\alatency\x12\x16\n" +
	"\x06jitter\x18\x03 \x01(\x01R\x06jitter\x12\x1f\n" +
	"\vpacket_loss\x18\x04 \x01(\x01R\n" +
	"packetLoss\x12\x1c\n" +
	"\tbandwidth\x18\x05 \x01(\x01R\tbandwidth\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"9\n" +
	"\vMetricsList\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.metrics.MetricsR\aentries2\x91\x01\n" +
	"\x0eMetricsService\x12B\n" +
	"\rSubmitMetrics\x12\x17.metrics.MetricsRequest\x1a\x18.metrics.MetricsResponse\x12;\n" +
	"\fFetchMetrics\x12\x15.metrics.FetchRequest\x1a\x14.metrics.MetricsListB\x15Z\x13pkg/api/proto;protob\x06proto3"

var (
	file_pkg_api_proto_metrics_proto_rawDescOnce sync.Once
	file_pkg_api_proto_metrics_proto_rawDescData []byte
)

func file_pkg_api_proto_metrics_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_metrics_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_metrics_proto_rawDesc), len(file_pkg_api_proto_metrics_proto_rawDesc)))
	})
	return file_pkg_api_proto_metrics_proto_rawDescData
}

var file_pkg_api_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_api_proto_metrics_proto_goTypes = []any{
	(*MetricsRequest)(nil),  // 0: metrics.MetricsRequest
	(*MetricsResponse)(nil), // 1: metrics.MetricsResponse
	(*FetchRequest)(nil),    // 2: metrics.FetchRequest
	(*Metrics)(nil),         // 3: metrics.Metrics
	(*MetricsList)(nil),     // 4: metrics.MetricsList
}
var file_pkg_api_proto_metrics_proto_depIdxs = []int32{
	3, // 0: metrics.MetricsList.entries:type_name -> metrics.Metrics
	0, // 1: metrics.MetricsService.SubmitMetrics:input_type -> metrics.MetricsRequest
	2, // 2: metrics.MetricsService.FetchMetrics:input_type -> metrics.FetchRequest
	1, // 3: metrics.MetricsService.SubmitMetrics:output_type -> metrics.MetricsResponse
	4, // 4: metrics.MetricsService.FetchMetrics:output_type -> metrics.MetricsList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_metrics_proto_init() }
func file_pkg_api_proto_metrics_proto_init() {
	if File_pkg_api_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_metrics_proto_rawDesc), len(file_pkg_api_proto_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_metrics_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_metrics_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_metrics_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_metrics_proto = out.File
	file_pkg_api_proto_metrics_proto_goTypes = nil
	file_pkg_api_proto_metrics_proto_depIdxs = nil
}
